### ISSUE TITLE
Package is not deployed to npm/yarn

### ISSUE THREAD

**Issue by DimaDK02** [entria/entria-deploy#4]
When I run `yarn global add @entria/deploy` (command from docs) I get
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@entria%2fdeploy: Not found".
```
Also [search on yarnpkg](https://yarnpkg.com/en/packages?q=%40entria%2Fdeploy&p=1) shows not result.

Are you about to deploy this package or should I use some another solution?

**Comment by sibelius** [comment]
I think before releasing the package, we should address the other 2/3 issues we have open

can you run locally and check if entria-deploy is good enough for you right now?

if it is, we can release to npm/yarn

**Comment by DimaDK24** [comment]
I installed it from github, but files, deployed to github, don't include built `.js` files, thus I couldn't run it.

Anyway, I found out that my deployment script (`serverless deploy`) already checks if deployment package was changed, so I don't need to do this check on my own.

But thank you for fast response!

**Comment by sibelius** [comment]
fixd
