### ISSUE TITLE
Add cli option for packages directory name

### ISSUE THREAD

**Issue by c-moss-talk** [entria/entria-deploy#5]
Hey, nice work @sibelius 👍 , as always, I can find your contributions whenever I go looking to solve a problem. 

I have a proposal. I am looking to solve a situation in which I need to trigger a workflow on directory changes for bit.dev. [Here is need.](https://stackoverflow.com/questions/59650139/bit-dev-workflow-without-dedicated-team-for-a-shared-library-and-with-code-revie/61557146#61557146).

Basically I won't be using changes to the `packages` directory to trigger the flow. So my proposal is to allow a command line option `[-d, --dir] <folder-name>`  to the cli to swap out the name for the default folder name `packages`.

Usage: 

```
  entria-deploy components --dir bit-staging
```
would you accept a PR?

btw, I saw comments about pipelines, but we have a self-hosted circle server so can't use that.

**Comment by sibelius** [comment]
We gonna accept a PR for this

**Comment by sibelius** [comment]
sorry for the delay, I think I fixed this on this https://github.com/entria/entria-deploy/pull/8

the cli now has 2 commands

```jsx
yarn entria-deploy changes $CIRCLECI_COMPARE_URL
```

returns a list of all changed files based on a compareUrl, so you can determine which files to tests in your pull request

---

```jsx
yarn entria-deploy hasChanged $CIRCLECI_COMPARE_URL components/a components/b
```

returns true if at least one path has changed, so you can decide if you build or deploy one of your packages or frontends
